name: animed_food1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para las imágenes
  assets:
    - assets/images/logo.png
    - assets/images/google_logo_colored.png
    - assets/images/phone_icon_green.png
    - assets/images/mail_icon_red.png
    # ... otras imágenes que puedas tener.

  # Para las fuentes
  fonts:
    - family: Inter
      fonts:
        # CORREGIDO: Nombres de archivo de fuentes Inter según tu imagen
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600

    - family: Heisei Maru Gothic Std
      fonts:
        # Asegúrate que el nombre del archivo de heiseimaru coincida exactamente
        - asset: assets/fonts/heiseimaru.otf # Si tu archivo es .ttf, cámbialo a .ttf
          weight: 800 # O el peso real de tu archivo de fuente
